set guioptions=a  " Turns off menu bars or something?
set guifont=FiraFlott:h20
set guicursor=a:blinkon0
colorscheme gruvbox
set bg=light

""" Auto-reload
autocmd! BufWritePost ~/.gvimrc source ~/.gvimrc
