set guioptions=a  " Turns off menu bars or something?
set guifont=Anonymous\ Pro:h18
set guicursor=a:blinkon0
colorscheme gruvbox
set background=light
let g:solarized_italic=0

""" Auto-reload
autocmd! BufWritePost gvimrc source ~/.gvimrc
